default:
  tags: [Sharepoint_docker_srvap5868_group]

stages:
  - build
  - deploy

variables:
  DOTNET_VERSION: "8.0"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"

# Сборка для тестового окружения
build_test:
  stage: build
  variables:
    config: Debug
  extends: .build

# Сборка для продакшн окружения
build_prod:
  stage: build
  variables:
    config: Release
  extends: .build
  when: manual

.build:
  stage: build
  image: 
    name: seis.rccf.ru:8015/sharepoint/dotnet/sdk:$DOTNET_VERSION
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  variables:
    http_proxy: "http://rccf.ru\\${HTTP_PROXY_USER}:${HTTP_PROXY_PASSWORD}@proxy.gslb.rccf.ru:8080"
    https_proxy: "http://rccf.ru\\${HTTP_PROXY_USER}:${HTTP_PROXY_PASSWORD}@proxy.gslb.rccf.ru:8080"
    no_proxy: "localhost,docker,127.0.0.1,0.0.0.0,rccf.ru,rencredit.ru"
    DOTNET_NUGET_SIGNATURE_VERIFICATION: "false"
    NUGET_CERT_REVOCATION_MODE: "offline"
    DOCKER_SECURITY_OPT: "seccomp=unconfined"
  script: |
    dotnet restore --no-cache
    dotnet build --configuration ${config}
    dotnet publish --configuration ${config} --output KPICatalog
  artifacts:
    paths:
      - KPICatalog/
      
# Деплой на тестовый сервер
deploy_test:
  stage: deploy
  extends: .deploy
  dependencies:
    - build_test
  variables:
    REMOTE_USER: ${TEST_USERNAME}
    REMOTE_PASS: ${TEST_PASSWORD}
    REMOTE_HOST: SRVWE670
    REMOTE_PATH: "C:\\inetpub"
    env: test
  when: manual

# Деплой на продакшн сервер
deploy_prod:
  stage: deploy
  extends: .deploy
  dependencies:
    - build_prod
  variables:
    REMOTE_USER: ${PROD_USERNAME}
    REMOTE_PASS: ${PROD_PASSWORD}
    REMOTE_HOST: SRVWE669
    REMOTE_PATH: "C:\\inetpub"
    env: production
  when: manual

.deploy:
  stage: deploy
  image: seis.rccf.ru:8015/sharepoint/deploy:latest
  script: |
    echo "Deploying to ${env} server"
    echo "Delete backup directory"
    sshpass -p "$REMOTE_PASS" ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "powershell.exe -Command \"if (Test-Path '${REMOTE_PATH}\\KPICatalog_backup') { Remove-Item -Recurse -Force '${REMOTE_PATH}\\KPICatalog_backup' }\"" || true
    echo "Backup directory was deleted successfully"
    echo "Make backup"
    sshpass -p "$REMOTE_PASS" ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "powershell.exe -Command \"Copy-Item -Recurse -Force '${REMOTE_PATH}\\KPICatalog' '${REMOTE_PATH}\\KPICatalog_backup'\""
    echo "Backup was created successfully"
    echo "Copy current project"
    sshpass -p "$REMOTE_PASS" scp -C -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -r KPICatalog ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}\\
    echo "Project was copied successfully"